### ISSUE TITLE
Driver page

### ISSUE THREAD

**Issue by AdaN6** [WiktorSzymczyk/wrwrum-final-project#6]

**Comment by WiktorSzymczyk** [comment]
V1
+The layout is completed. It shows a summary of the driver
![image](https://user-images.githubusercontent.com/74505952/210399365-dc796b33-e4c0-4ddb-8a3f-37deee4d4917.png)
+The button with the details transfers user to the details page correctly.

-Need to ensure that the user can change the season for v2. currently the base is 2023 for this page. One of the possible ways to do it is to create mapping function for each of the seasons and make a condition to make it visible/invisible depending on the season chosen.
